# Generated by Django 5.2.14 on 2026-05-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('available_beds', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(max_length=20)),
                ('arrived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_notifications', to='emergencies.emergency')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_patients', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
