# Generated by Django 5.2.14 on 2026-05-28 20:25

import apps.emergencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.emergencies.models.emergency_image_path)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to=apps.emergencies.models.emergency_voice_path)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('on_the_way', 'On the way'), ('arrived_at_scene', 'Arrived at scene'), ('patient_picked_up', 'Patient picked up'), ('at_hospital', 'At hospital'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('on_the_way', 'On the way'), ('arrived_at_scene', 'Arrived at scene'), ('patient_picked_up', 'Patient picked up'), ('at_hospital', 'At hospital'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
