# Generated by Django 5.2.15 on 2026-07-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='emergency',
            name='priority',
            field=models.CharField(default='P3', max_length=2),
        ),
        migrations.AddField(
            model_name='emergency',
            name='severity_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
