# Generated by Django 5.2.15 on 2026-07-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergencies", "0003_emergency_confidence_emergency_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="recommended_responder_type",
            field=models.CharField(default="ambulance", max_length=20),
        ),
    ]
