# Generated by Django 5.2.15 on 2026-07-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergencies", "0004_emergency_recommended_responder_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="estimated_response_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="emergency",
            name="possible_conditions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="emergency",
            name="recommended_hospital_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="emergency",
            name="required_units",
            field=models.JSONField(default=list),
        ),
    ]
